Bootstrap an app using SveleteKit!
Ran `npm init svelte@next`

* Found out that this doesn't work with `12.18.4` :goberserk:  bummer!
Switching to current LTS (`14.18.0`) fixed the issue.

```
Z:\code\learn-svelte (master -> origin) (learn-svelte@0.0.1)
λ npm run dev -- --open

> learn-svelte@0.0.1 dev Z:\code\learn-svelte
> svelte-kit dev "--open"

(node:26680) ExperimentalWarning: The ESM module loader is experimental.
(node:26680) UnhandledPromiseRejectionWarning:
file:///Z:/code/learn-svelte/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:261
import { createMakeHot } from "svelte-hmr";
^^^^^^^^^^^^^
SyntaxError: The requested module 'svelte-hmr' is expected to be of type
CommonJS, which does not support named exports. CommonJS modules can be
imported by importing the default export.
For example:
import pkg from 'svelte-hmr';
const { createMakeHot } = pkg;
at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
at async ModuleJob.run (internal/modules/esm/module_job.js:136:20)
at async Loader.import (internal/modules/esm/loader.js:179:24)
at async
file:///Z:/code/learn-svelte/node_modules/@sveltejs/kit/dist/cli.js:833:19
(node:26680) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was not
handled with .catch(). To terminate the node process on unhandled
promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).
(rejection id: 1)
(node:26680) [DEP0018] DeprecationWarning: Unhandled promise rejections
are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.
```